### ISSUE TITLE
Add util as a feature to noodles crate

### ISSUE THREAD

**Issue by holtgrewe** [zaeleus/noodles#159]
Hi, I'm using noodles with features vcf, bcf, csi, fasta, bgzf, and tabix.

Also, I'm using noodles-util as there is no util feature.

My Cargo.toml fragment looks as follows.

```toml
noodles = { version = "0.33.0", features = ["vcf", "bcf", "csi", "fasta", "bgzf", "tabix"] }
noodles-util = { version = "0.5.0", features = ["noodles-bcf", "noodles-bgzf", "noodles-vcf", "variant"] }
```

Also, I use dependabot.

Dependabot will not create independent PRs for the two crates and both will fail as if only one is updated then the vcf record from noodles-util will not match the one from noodles.

This could be resolved by adding util as a feature just like vcf and bcf are.

Would this be possible?

**Comment by zaeleus** [comment]
I don't think this would solve your issue with Dependabot. noodles-util is not included in the noodles meta crate because 1) it has no default features, and 2) Cargo does not allow features to be transitively enabled. So if noodles-util were to be added to noodles, you would still have to explicitly add noodles-util as a dependency to enable the selected features. For example,

```toml
noodles = { version = "0.34.0", features = ["util"] }
noodles-util = { version = "0.6.0", features = ["variant"] }
```

**Comment by holtgrewe** [comment]
Thank you for the quick reply. So my best way forward would be to set noodles to be ignored in dependabot and update manually. Fair enough.

**Comment by holtgrewe** [comment]
Actually, the best way is to use `.github/dependabot.yml` and setup a group that captures `noodles-*` and all "reverse transitive" dependencies as done [here](https://github.com/bihealth/hgvs-rs/commit/b5399215294e555df06bc78c7ffca4d71acb4c75).

```yaml
    groups:
      noodles:
        patterns:
          - "your-inverse-transitive-dep-or-remove-this-line"
          - "noodles-*"
```
