### ISSUE TITLE
question: how to convert cigar from bytes. 

### ISSUE THREAD

**Issue by cauliyang** [zaeleus/noodles#233]
now the lib includes two kinds of `Cigar` Struct. but it seems like none of them can be constructed from bytes. 

This cigar `pub struct Cigar<'a>(&'a [u8]);` provides a new method but it is not a public function.  https://github.com/zaeleus/noodles/blob/af84e95376b2b757951aca734f27e2f4c98c38bf/noodles-sam/src/record/cigar.rs#L10

Could we export the `new` method or `parse_cigar`?  so that we can construct a `Cigar` from bytes like this : 

```rust
let cigar = Cigar::new(b"11M120N");
```

If needed. I can open a new pr. 

The libs I use now: 
```toml

noodles-bam = "0.55.0"
noodles-bgzf = "0.26.0"
noodles-csi = "0.30.0"
noodles-fasta = "0.32.0"
noodles-fastq = "0.10.0"
noodles-sam = "0.52.0"
noodles-core = "0.14"


```
Thanks for your great help!
